from typing import Protocol, Iterable
from uuid import UUID

from renovation_cost_tracker.domain.models import User, Project, Expense


class IUserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def get(self, id: UUID) -> User | None: ...
    def find_by_email(self, email: str) -> User | None: ...


class IProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...
    def get(self, id: UUID) -> Project | None: ...
    def list_by_user(self, user_id: UUID) -> Iterable[Project]: ...


class IExpenseRepository(Protocol):
    def save(self, expense: Expense) -> None: ...
    def get(self, id: UUID) -> Expense | None: ...
    def list_by_project(self, project_id: UUID) -> Iterable[Expense]: ...
    def delete(self, id: UUID) -> None: ...